version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./app:/var/www/html
    networks:
      - laravel

  postgres:
    image: postgres:latest
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  postgres_data:

networks:
  laravel:
    driver: bridge
